package com.mgr.common.data;

// Generated May 27, 2015 2:33:14 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.math.BigDecimal;
import java.sql.Timestamp;

/**
 * Odpowiednik tabeli ALERTY_POMYLONE_DOSTAWY_ESPER AlertyPomyloneDostawyEsper
 * generated by hbm2java
 */
@Entity
@Table(name = "ALERTY_POMYLONE_DOSTAWY_ESPER")
public class AlertyPomyloneDostawyEsper implements java.io.Serializable,
        EsperAlertData {

    private String id;
    private BigDecimal priority;
    private Timestamp updateDate;

    public AlertyPomyloneDostawyEsper() {
    }

    public AlertyPomyloneDostawyEsper(String id, BigDecimal priority,
                                      Timestamp updateDate) {
        this.id = id;
        this.priority = priority;
        this.updateDate = updateDate;
    }

    @Id
    @Column(name = "ID", unique = true, nullable = false, length = 50)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "PRIORITY", nullable = false, precision = 22, scale = 0)
    public BigDecimal getPriority() {
        return this.priority;
    }

    public void setPriority(BigDecimal priority) {
        this.priority = priority;
    }

    @Column(name = "UPDATE_DATE", nullable = false)
    public Timestamp getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(Timestamp updateDate) {
        this.updateDate = updateDate;
    }

}
