package com.mgr.common.data;

// Generated May 27, 2015 2:33:14 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;
import java.math.BigDecimal;

/**
 * Odpowiednik PK ALERTY_NISKA_JAKOSC_ESPER_ID AlertyNiskaJakoscEsperId
 * generated by hbm2java
 */
@Embeddable
public class AlertyNiskaJakoscEsperId implements java.io.Serializable {

    private String seria;
    private BigDecimal poziom;

    public AlertyNiskaJakoscEsperId() {
    }

    public AlertyNiskaJakoscEsperId(String seria, BigDecimal poziom) {
        this.seria = seria;
        this.poziom = poziom;
    }

    @Column(name = "SERIA", nullable = false, length = 50)
    public String getSeria() {
        return this.seria;
    }

    public void setSeria(String seria) {
        this.seria = seria;
    }

    @Column(name = "POZIOM", nullable = false, precision = 22, scale = 0)
    public BigDecimal getPoziom() {
        return this.poziom;
    }

    public void setPoziom(BigDecimal poziom) {
        this.poziom = poziom;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof AlertyNiskaJakoscEsperId))
            return false;
        AlertyNiskaJakoscEsperId castOther = (AlertyNiskaJakoscEsperId) other;

        return ((this.getSeria() == castOther.getSeria()) || (this.getSeria() != null
                && castOther.getSeria() != null && this.getSeria().equals(
                castOther.getSeria())))
                && ((this.getPoziom() == castOther.getPoziom()) || (this
                .getPoziom() != null && castOther.getPoziom() != null && this
                .getPoziom().equals(castOther.getPoziom())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result
                + (getSeria() == null ? 0 : this.getSeria().hashCode());
        result = 37 * result
                + (getPoziom() == null ? 0 : this.getPoziom().hashCode());
        return result;
    }

}
