package com.mgr.common.data;

// Generated May 27, 2015 2:33:14 PM by Hibernate Tools 4.0.0

import javax.persistence.*;
import java.math.BigDecimal;
import java.sql.Timestamp;

/**
 * Odpowiednik tabeli ALERTY_NISKA_WYD_PROCESU_ESPER AlertyNiskaWydProcesuEsper
 * generated by hbm2java
 */
@Entity
@Table(name = "ALERTY_NISKA_WYD_PROCESU_ESPER")
public class AlertyNiskaWydProcesuEsper implements java.io.Serializable,
        EsperAlertData {

    private String seria;
    private BigDecimal priority;
    private Timestamp updateDate;

    public AlertyNiskaWydProcesuEsper() {
    }

    public AlertyNiskaWydProcesuEsper(String seria, BigDecimal priority,
                                      Timestamp updateDate) {
        this.seria = seria;
        this.priority = priority;
        this.updateDate = updateDate;
    }

    @Id
    @Column(name = "SERIA", unique = true, nullable = false, length = 50)
    public String getSeria() {
        return this.seria;
    }

    public void setSeria(String seria) {
        this.seria = seria;
    }

    @Column(name = "PRIORITY", nullable = false, precision = 22, scale = 0)
    public BigDecimal getPriority() {
        return this.priority;
    }

    public void setPriority(BigDecimal priority) {
        this.priority = priority;
    }

    @Column(name = "UPDATE_DATE", nullable = false)
    public Timestamp getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(Timestamp updateDate) {
        this.updateDate = updateDate;
    }

    @Override
    @Transient
    public Object getId() {
        return getSeria();
    }

}
